#! /bin/sh
mkdir -p result/test
mkdir -p result/train
cd src
# run scripts
echo "start analysis train dataset"
python main.py "train" 10 | tee trainlog.log
python main.py "train" 5 | tee trainlog.log
echo "end finished train dataset"

echo "start analysis test dataset"
python main.py "test" 10 | tee testlog.log
python main.py "test" 5 | tee testlog.log
echo "end finished test dataset"
cd ..

tar -cvf result.tar  result